name: coffee_app
description: "A new Flutter project."
publish_to: "none"
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  bloc: ^9.0.0
  uuid: ^4.5.1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2


dev_dependencies:
  drift_dev: ^2.26.0
  retrofit_generator: "^9.0.0" # for Dart 3.3 use ^9.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/icons/
    - assets/svg/
    - assets/img/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
